angular.module('FitBoard').controller('AdminCtrl', function($scope) {
	'use strict';

  // Initialization
  $scope.category = 'elite';
  $scope.sex      = 'male';
  $scope.place    = 'placeA';
  $scope.score    = 'pointsA';
  $scope.wod      = 'wod1';

  $scope.gridOptions = {};
  $scope.gridOptions.data = [];
  $scope.gridOptions.enableColumnResizing = true;
  $scope.gridOptions.enableFiltering = true;
  $scope.gridOptions.enableCellEdit = false;
  $scope.gridOptions.enableGridMenu = true;
  $scope.gridOptions.rowHeight = 38;
  $scope.gridOptions.onRegisterApi = function(gridApi) {
    $scope.gridApi = gridApi;
  };

  $scope.refresh = function() {
    $scope.gridApi.core.clearAllFilters();
  }

$scope.editAthlete = function(startNo, judgeNo, scoreWod) {
  //TODO: change judgeNo and scoreWod for the athlete (find him by startNo)
  // 1) find the athlete by startNo
  // 2) change the values of judgeNo and scoreWod on server
  // 3) refresh the data in ui-grid if it is not done automatically
  // var findExpr = $scope.athletes.some(function(athl) { return athl.startNo === startNo;});
  // var athleteIdx = $scope.athletes.findIndex(findExpr);
  // $scope.athletes.at(athleteIdx).judgeNo = judgeNo;
  // $scope.athletes.at(athleteIdx).score = scoreWod;
  // $scope.gridApi.core.refresh();
};

  $scope.gridOptions.columnDefs = [
		{
      name: 'Place',
      field: $scope.place,
      enableFiltering: false
    },
    {
      name:'Start number',
      field: 'startNo',
      enableFiltering: true
    },
    {
      name:'Full name',
      field: 'firstName',
      enableFiltering: true
		},
    {
      name:'Category',
      field: 'category',
      enableFiltering: false,
      filter: {
        noTerm: true,
        condition: function(searchTerm, cellValue) {
          return cellValue === $scope.category;
        }
      }
    },
		{
      name:'Sex',
			field: 'sex',
      enableFiltering: false,
      filter: {
        noTerm: true,
        condition: function(searchTerm, cellValue) {
          return cellValue === $scope.sex;
        }
      }
		},
		{
      name:'Score',
      field: $scope.score,
      enableFiltering: false
      // enableFiltering: false,
      // filter: {
      //   noTerm: true,
      //   condition: function(searchTerm, cellValue) {
      //     return cellValue === $scope.sex;
      //   }
      // }
		},
		{
      name:'Judge number',
      type: 'number',
      enableFiltering: true
		}
  ];



 ////////////////////////// Athletes  ////////////////////////////////////
  $scope.athletes = [
      {
        firstName: 'Pepa',
        lastName: 'Veliky 1',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 1,
        pointsA: '06:50',
        pointsB: '100',
        pointsO: 3,
        placeA: 4,
        placeB: 1,
        placeOV: 2,
        score: 1,
        scoreWod1: 2
      },
      {
        firstName: 'Adam',
        lastName: 'Zeleny 2',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 2,
        pointsA: '07:00',
        pointsB: '90',
        pointsO: 4,
        placeA: 1,
        placeB: 2,
        placeOV: 1,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 3',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 3,
        pointsA: '90',
        pointsB: '80',
        pointsO: 6,
        placeA: 3,
        placeB: 3,
        placeOV: 3,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 4',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '80',
        pointsB: '70',
        pointsO: 8,
        placeA: 2,
        placeB: 4,
        placeOV: 4,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 5',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '70',
        pointsB: '60',
        pointsO: 10,
        placeA: 5,
        placeB: 5,
        placeOV: 5,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 6',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '60',
        pointsB: '50',
        pointsO: 12,
        placeA: 6,
        placeB: 6,
        placeOV: 6,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 7',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '50',
        pointsB: '40',
        pointsO: 14,
        placeA: 7,
        placeB: 7,
        placeOV: 7,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 8',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '40',
        pointsB: '30',
        pointsO: 16,
        placeA: 8,
        placeB: 8,
        placeOV: 8,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 9',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '30',
        pointsB: '20',
        pointsO: 18,
        placeA: 9,
        placeB: 9,
        placeOV: 9,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 10',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '20',
        pointsB: '10',
        pointsO: 20,
        placeA: 10,
        placeB: 10,
        placeOV: 10,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 11',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '10',
        pointsB: '0',
        pointsO: 22,
        placeA: 11,
        placeB: 11,
        placeOV: 11,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 12',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 12,
        placeB: 12,
        placeOV: 12,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 13',
        sex: 'male',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 13,
        placeB: 13,
        placeOV: 13,
        score: 0
      },
//// WOMEN
{
        firstName: 'Athlete',
        lastName: 'Name 1',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 1,
        pointsA: '06:50',
        pointsB: '100',
        pointsO: 3,
        placeA: 4,
        placeB: 1,
        placeOV: 2,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 2',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '07:00',
        pointsB: '90',
        pointsO: 4,
        placeA: 1,
        placeB: 2,
        placeOV: 1,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 3',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '90',
        pointsB: '80',
        pointsO: 6,
        placeA: 3,
        placeB: 3,
        placeOV: 3,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 4',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '80',
        pointsB: '70',
        pointsO: 8,
        placeA: 2,
        placeB: 4,
        placeOV: 4,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 5',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '70',
        pointsB: '60',
        pointsO: 10,
        placeA: 5,
        placeB: 5,
        placeOV: 5,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 6',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '60',
        pointsB: '50',
        pointsO: 12,
        placeA: 6,
        placeB: 6,
        placeOV: 6,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 7',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '50',
        pointsB: '40',
        pointsO: 14,
        placeA: 7,
        placeB: 7,
        placeOV: 7,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 8',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '40',
        pointsB: '30',
        pointsO: 16,
        placeA: 8,
        placeB: 8,
        placeOV: 8,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 9',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '30',
        pointsB: '20',
        pointsO: 18,
        placeA: 9,
        placeB: 9,
        placeOV: 9,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 10',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '20',
        pointsB: '10',
        pointsO: 20,
        placeA: 10,
        placeB: 10,
        placeOV: 10,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 11',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: '10',
        pointsB: '0',
        pointsO: 22,
        placeA: 11,
        placeB: 11,
        placeOV: 11,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 12',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 12,
        placeB: 12,
        placeOV: 12,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 13',
        sex: 'female',
        gym: 'independent',
        category: 'elite',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 13,
        placeB: 13,
        placeOV: 13,
        score: 0
      },
//// OPEN
{
        firstName: 'Athlete',
        lastName: 'Name 1',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 1,
        pointsA: '06:50',
        pointsB: '100',
        pointsO: 3,
        placeA: 4,
        placeB: 1,
        placeOV: 2,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 2',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '07:00',
        pointsB: '90',
        pointsO: 4,
        placeA: 1,
        placeB: 2,
        placeOV: 1,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 3',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '90',
        pointsB: '80',
        pointsO: 6,
        placeA: 3,
        placeB: 3,
        placeOV: 3,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 4',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '80',
        pointsB: '70',
        pointsO: 8,
        placeA: 2,
        placeB: 4,
        placeOV: 4,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 5',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '70',
        pointsB: '60',
        pointsO: 10,
        placeA: 5,
        placeB: 5,
        placeOV: 5,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 6',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '60',
        pointsB: '50',
        pointsO: 12,
        placeA: 6,
        placeB: 6,
        placeOV: 6,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 7',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '50',
        pointsB: '40',
        pointsO: 14,
        placeA: 7,
        placeB: 7,
        placeOV: 7,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 8',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '40',
        pointsB: '30',
        pointsO: 16,
        placeA: 8,
        placeB: 8,
        placeOV: 8,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 9',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '30',
        pointsB: '20',
        pointsO: 18,
        placeA: 9,
        placeB: 9,
        placeOV: 9,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 10',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '20',
        pointsB: '10',
        pointsO: 20,
        placeA: 10,
        placeB: 10,
        placeOV: 10,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 11',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '10',
        pointsB: '0',
        pointsO: 22,
        placeA: 11,
        placeB: 11,
        placeOV: 11,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 12',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 12,
        placeB: 12,
        placeOV: 12,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 13',
        sex: 'male',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 13,
        placeB: 13,
        placeOV: 13,
        score: 0
      },
/// OPEN WOMEN
{
        firstName: 'Athlete',
        lastName: 'Name 1',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 1,
        pointsA: '06:50',
        pointsB: '100',
        pointsO: 3,
        placeA: 4,
        placeB: 1,
        placeOV: 2,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 2',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '07:00',
        pointsB: '90',
        pointsO: 4,
        placeA: 1,
        placeB: 2,
        placeOV: 1,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 3',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '90',
        pointsB: '80',
        pointsO: 6,
        placeA: 3,
        placeB: 3,
        placeOV: 3,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 4',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '80',
        pointsB: '70',
        pointsO: 8,
        placeA: 2,
        placeB: 4,
        placeOV: 4,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 5',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '70',
        pointsB: '60',
        pointsO: 10,
        placeA: 5,
        placeB: 5,
        placeOV: 5,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 6',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '60',
        pointsB: '50',
        pointsO: 12,
        placeA: 6,
        placeB: 6,
        placeOV: 6,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 7',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '50',
        pointsB: '40',
        pointsO: 14,
        placeA: 7,
        placeB: 7,
        placeOV: 7,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 8',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '40',
        pointsB: '30',
        pointsO: 16,
        placeA: 8,
        placeB: 8,
        placeOV: 8,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 9',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '30',
        pointsB: '20',
        pointsO: 18,
        placeA: 9,
        placeB: 9,
        placeOV: 9,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 10',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '20',
        pointsB: '10',
        pointsO: 20,
        placeA: 10,
        placeB: 10,
        placeOV: 10,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 11',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: '10',
        pointsB: '0',
        pointsO: 22,
        placeA: 11,
        placeB: 11,
        placeOV: 11,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 12',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 12,
        placeB: 12,
        placeOV: 12,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 13',
        sex: 'female',
        gym: 'independent',
        category: 'open',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 13,
        placeB: 13,
        placeOV: 13,
        score: 0
      },
// MASTERS
{
        firstName: 'Athlete',
        lastName: 'Name 1',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 1,
        pointsA: '06:50',
        pointsB: '100',
        pointsO: 3,
        placeA: 4,
        placeB: 1,
        placeOV: 2,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 2',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '07:00',
        pointsB: '90',
        pointsO: 4,
        placeA: 1,
        placeB: 2,
        placeOV: 1,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 3',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '90',
        pointsB: '80',
        pointsO: 6,
        placeA: 3,
        placeB: 3,
        placeOV: 3,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 4',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '80',
        pointsB: '70',
        pointsO: 8,
        placeA: 2,
        placeB: 4,
        placeOV: 4,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 5',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '70',
        pointsB: '60',
        pointsO: 10,
        placeA: 5,
        placeB: 5,
        placeOV: 5,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 6',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '60',
        pointsB: '50',
        pointsO: 12,
        placeA: 6,
        placeB: 6,
        placeOV: 6,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 7',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '50',
        pointsB: '40',
        pointsO: 14,
        placeA: 7,
        placeB: 7,
        placeOV: 7,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 8',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '40',
        pointsB: '30',
        pointsO: 16,
        placeA: 8,
        placeB: 8,
        placeOV: 8,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 9',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '30',
        pointsB: '20',
        pointsO: 18,
        placeA: 9,
        placeB: 9,
        placeOV: 9,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 10',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '20',
        pointsB: '10',
        pointsO: 20,
        placeA: 10,
        placeB: 10,
        placeOV: 10,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 11',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '10',
        pointsB: '0',
        pointsO: 22,
        placeA: 11,
        placeB: 11,
        placeOV: 11,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 12',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 12,
        placeB: 12,
        placeOV: 12,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 13',
        sex: 'male',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 13,
        placeB: 13,
        placeOV: 13,
        score: 0
      },
// MASTERS WOMEN
{
        firstName: 'Athlete',
        lastName: 'Name 1',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 1,
        pointsA: '06:50',
        pointsB: '100',
        pointsO: 3,
        placeA: 4,
        placeB: 1,
        placeOV: 2,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 2',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '07:00',
        pointsB: '90',
        pointsO: 4,
        placeA: 1,
        placeB: 2,
        placeOV: 1,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 3',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '90',
        pointsB: '80',
        pointsO: 6,
        placeA: 3,
        placeB: 3,
        placeOV: 3,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 4',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '80',
        pointsB: '70',
        pointsO: 8,
        placeA: 2,
        placeB: 4,
        placeOV: 4,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 5',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '70',
        pointsB: '60',
        pointsO: 10,
        placeA: 5,
        placeB: 5,
        placeOV: 5,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 6',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '60',
        pointsB: '50',
        pointsO: 12,
        placeA: 6,
        placeB: 6,
        placeOV: 6,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 7',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '50',
        pointsB: '40',
        pointsO: 14,
        placeA: 7,
        placeB: 7,
        placeOV: 7,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 8',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '40',
        pointsB: '30',
        pointsO: 16,
        placeA: 8,
        placeB: 8,
        placeOV: 8,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 9',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '30',
        pointsB: '20',
        pointsO: 18,
        placeA: 9,
        placeB: 9,
        placeOV: 9,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 10',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '20',
        pointsB: '10',
        pointsO: 20,
        placeA: 10,
        placeB: 10,
        placeOV: 10,
        score: 1
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 11',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: '10',
        pointsB: '0',
        pointsO: 22,
        placeA: 11,
        placeB: 11,
        placeOV: 11,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 12',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 12,
        placeB: 12,
        placeOV: 12,
        score: 0
      },
      {
        firstName: 'Athlete',
        lastName: 'Name 13',
        sex: 'female',
        gym: 'independent',
        category: 'masters',
        startNo: 12,
        pointsA: 0,
        pointsB: 0,
        pointsO: 0,
        placeA: 13,
        placeB: 13,
        placeOV: 13,
        score: 0
      }
    ];
});
